apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multitool
  name: multitool
spec:
  containers:
  - image: przemekmalak/multitool
    name: multitool
    env:
    - name: RETURN_TEXT
      value: "returned text"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always

